### ISSUE TITLE
Write-log error

### ISSUE THREAD

**Issue by Pierre450** [tesorion/TCERT-Cumulonimbus-UAL_Extractor#1]
In your script where do these functions come from?
. "$PSScriptRoot\..\Functions\Get-Timestamp.ps1"
. "$PSScriptRoot\..\Functions\Write-log.ps1"

I tried getting Write-Log from PSGallery, but still getting errors. Did you write your own functions?

**Comment by 0x534a** [comment]
I faced the same issue. Seems that the files with the imported functions were simply not provided in this repository. Since this repo does not seem to be maintained any more, I created a fork that fixes the bugs. You can find the fixed version in https://github.com/0x534a/TCERT-Cumulonimbus-UAL_Extractor.

**Comment by Tesorion-CERT** [comment]
This has been solved by adding the missing files to the repository.
